[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mediatool"
authors = [{name = "BaoHengtao", email = "baohengtao@users.noreply.github.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/baohengtao/mediatool"


[project.scripts]
videotool = 'mediatool.video:app'
audiotool = 'mediatool.audio:app'
